server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boop?currentSchema=public
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: boop



security:
  jwt:
    secret: this-is-my-super-secret-key-32-chars-long
    expiry-ms: 86400000


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG
    org.springframework.web: DEBUG
    io.jsonwebtoken: TRACE

springdoc:
  packages-to-scan: boop
  swagger-ui:
   persistAuthorization: true

