server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boop?currentSchema=public
    username: debug
    password: debug
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public



security:
  jwt:
    secret: boop-secret-key-change-later
    expiry-ms: 86400000


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema: DEBUG

springdoc:
  packages-to-scan: boop
